---
apiVersion: v1
kind: Service
metadata:
  name: cds-frontend-ui
  labels:
    app: cds-frontend-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: cds-frontend-ui
    version: v1
