---
apiVersion: v1
kind: Service
metadata:
  name: cds-frontend-ui-lb
  labels:
    app: cds-frontend-ui
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: cds-frontend-ui
    version: v1
