steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/$PROJECT_ID/datashare-ui:$TAG_NAME"
  - "--file=./Dockerfile"
  - .
images:
  - "gcr.io/$PROJECT_ID/datashare-ui:$TAG_NAME"

