steps:
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['install']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'node:10.20.1'
  dir: 'ingestion/batch'
  entrypoint: 'npm'
  args: ['install']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'node:10.20.1'
  dir: 'ingestion/batch'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
options:
 logging: CLOUD_LOGGING_ONLY