steps:
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12.11.1'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12.11.1'
  dir: 'ingestion/function'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['run', 'test', '--', '--runCloudTests']
- name: 'node:12.11.1'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: ['run', 'test', '--', '--runCloudTests']
- name: 'node:8.16.2'
  dir: 'ingestion/function'
  entrypoint: 'npm'
  args: ['run', 'test', '--', '--runCloudTests']
- name: 'gcr.io/bqds-ci/integration-test'
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'BRANCH=$BRANCH_NAME'
  dir: 'tests/bin'
  entrypoint: 'bash'
  args: ['./run.sh']