steps:
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12.11.1'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:8.16.2'
  dir: 'ingestion/batch'
  entrypoint: 'npm'
  args: ['install']
- name: gcr.io/cloud-builders/gcloud
  dir: 'shared'
  args:
  - kms
  - decrypt
  - --ciphertext-file=/workspace/shared/ciphertexts/client_secret.json.enc
  - --plaintext-file=/workspace/shared/ciphertexts/client_secret.json
  - --location=global
  - --keyring=bqds-cloud-build-ring
  - --key=bqds-cloud-build
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
  env: ['GOOGLE_APPLICATION_CREDENTIALS=/workspace/shared/ciphertexts/client_secret.json']
- name: 'node:12.11.1'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
- name: 'node:8.16.2'
  dir: 'ingestion/batch'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
