steps:
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12.11.1'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:8.16.2'
  dir: 'ingestion/function'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12.11.1'
  dir: 'shared'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
- name: 'node:12.11.1'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
- name: 'node:8.16.2'
  dir: 'ingestion/function'
  entrypoint: 'npm'
  args: ['run', 'cloudtest']
