steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: [run', 'run', 'install']
- name: 'gcr.io/cloud-builders/npm'
  dir: 'entitlements/bqdsEntitlements'
  entrypoint: 'npm'
  args: [run', 'test', '--', '--runCloudTests']
- name: 'gcr.io/bqds-ci/integration-test'
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'BRANCH=$BRANCH_NAME'
  dir: 'tests/bin'
  entrypoint: 'bash'
  args: ['./run.sh']