steps:
- name: gcr.io/cloud-builders/git
  args: ['show', '269fc500ca72aead71957ab68769da72902d4a5c']
- name: 'gcr.io/bqds-ci/integration-test'
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'BRANCH=$BRANCH_NAME'
  dir: 'tests/bin'
  entrypoint: 'bash'
  args: ['./run.sh']