---
apiVersion: v1
kind: Service
metadata:
  name: cds-api-spot-service-lb
  labels:
    app: cds-api-spot-service
spec:
  type: LoadBalancer
  ports:
    - port: 5555
      name: http
      targetPort: 5555
  selector:
    app: cds-api-spot-service
    version: v1
