---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
data:
  FULFILLMENT_CONFIG_BUCKET_NAME: chrispage-dev-bqds-test
  FULFILLMENT_CONFIG_PUBSUB_TOPIC_NAME: bqds-spot-fulfillments
  FULFILLMENT_CONFIG_PUBSUB_SUBSCRIPTION_NAME: "projects/chrispage-dev/subscriptions/bqds-spot-fulfillments-worker"
