---
apiVersion: v1
kind: Service
metadata:
  name: cdmc-publisher-service
  labels:
    app: cdmc-publisher-service
spec:
  type: ClusterIP
  ports:
    - protocol: UDP
      port: 50000
      name: multicast
  selector:
    app: cdmc-publisher-service
    version: v1
