---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-data-producers
  namespace: datashare-apis
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods:
        - GET
        paths:
        - /v1alpha/datasets?*
        - /v1alpha/procurements
        - /v1alpha/procurements?*
        - /v1alpha/views
    - operation:
        methods:
        - POST
        paths:
        - /v1alpha/accounts:reset
        - /v1alpha/accounts:syncMarketplace
        - /v1alpha/admin:initSchema
        - /v1alpha/admin:syncResources
        - /v1alpha/datasets
        - /v1alpha/procurements/approve
    - operation:
        methods:
        - GET
        - POST
        paths:
        - /v1alpha/accounts
        - /v1alpha/policies
    - operation:
        methods:
        - GET
        - PUT
        - DELETE
        paths:
        - /v1alpha/accounts/*
        - /v1alpha/policies/*
    - operation:
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        paths:
        - /v1alpha/datasets/*
    when:
    - key: request.auth.claims[email]
      values: [$DATA_PRODUCERS]
