---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-marketplace-service-account
  namespace: datashare-apis
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods:
        - POST
        paths:
        # BEGIN: Backwards compatibility for marketplace
        - exact: "/v1alpha/projects/$PROJECT_ID/accounts:register"
        - exact: "/v1alpha/projects/$PROJECT_ID/procurements:myProducts"
        # END: Backwards compatibility for marketplace
        - /v1alpha/accounts:register
        - /v1alpha/procurements:myProducts
    - operation:
        methods:
        - GET
        paths:
        # BEGIN: Backwards compatibility for marketplace
        - /v1alpha/projects/$PROJECT_ID/procurements:myProducts?*
        # END: Backwards compatibility for marketplace
        - /v1alpha/procurements:myProducts?*
