---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-data-producers
  namespace: datashare-apis
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
      methods: ["GET,POST,PUT,DELETE"]
      paths: ["/v1alpha/projects/$PROJECT_ID/accounts*, /v1alpha/projects/$PROJECT_ID/accounts/*"]
    - operation:
      methods: ["GET,POST,PUT,DELETE"]
      paths: ["/v1alpha/projects/$PROJECT_ID/policies*, /v1alpha/projects/$PROJECT_ID/policies/*"]
    - operation:
      methods: ["GET,POST,PUT,DELETE"]
      paths: ["/v1alpha/projects/$PROJECT_ID/datasets*, /v1alpha/projects/$PROJECT_ID/datasets/*"]
    - operation:
      methods: ["POST"]
      paths: ["/v1alpha/projects/$PROJECT_ID/admin*, /v1alpha/projects/$PROJECT_ID/admin/*"]
    - operation:
      methods: ["POST"]
      paths: ["/v1alpha/projects/$PROJECT_ID/auth*, /v1alpha/projects/$PROJECT_ID/auth:isDataProducer"]
    - operation:
      methods: ["GET"]
      paths: ["/v1alpha/projects/$PROJECT_ID/products*, /v1alpha/projects/$PROJECT_ID/products/*"]
    - operation:
      methods: ["GET,POST"]
      paths: ["/v1alpha/projects/$PROJECT_ID/procurements*, /v1alpha/projects/$PROJECT_ID/procurements/*"]
    - operation:
      methods: ["GET,POST"]
      paths: ["/v1alpha/projects/$PROJECT_ID/spots*, /v1alpha/projects/$PROJECT_ID/spots/*"]
  - when:
    - key: request.auth.claims[iss]
      values:
      - accounts.google.com
      - https://accounts.google.com
      - https://securetoken.google.com/$PROJECT_ID
    - key: request.auth.claims[email]
      values: ["$DATA_PRODUCERS"]
