---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-data-producers
  namespace: datashare-apis
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods:
        - GET
        paths:
        - /v1alpha/projects/$PROJECT_ID/datasets?*
        - /v1alpha/projects/$PROJECT_ID/procurements
        - /v1alpha/projects/$PROJECT_ID/procurements?*
        - /v1alpha/projects/$PROJECT_ID/views
    - operation:
        methods:
        - POST
        paths:
        - /v1alpha/projects/$PROJECT_ID/accounts:reset
        - /v1alpha/projects/$PROJECT_ID/accounts:syncMarketplace
        - /v1alpha/projects/$PROJECT_ID/admin:initSchema
        - /v1alpha/projects/$PROJECT_ID/admin:syncResources
        - /v1alpha/projects/$PROJECT_ID/auth:isDataProducer
        - /v1alpha/projects/$PROJECT_ID/datasets
        - /v1alpha/projects/$PROJECT_ID/procurements/approve
    - operation:
        methods:
        - GET
        - POST
        paths:
        - /v1alpha/projects/$PROJECT_ID/accounts
        - /v1alpha/projects/$PROJECT_ID/policies
    - operation:
        methods:
        - GET
        - PUT
        - DELETE
        paths:
        - /v1alpha/projects/$PROJECT_ID/accounts/*
        - /v1alpha/projects/$PROJECT_ID/policies/*
    - operation:
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        paths:
        - /v1alpha/projects/$PROJECT_ID/datasets/*
    when:
    - key: request.auth.claims[email]
      values: [$DATA_PRODUCERS]
