---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-data-producers
  namespace: datashare-apis
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["OPTIONS", "GET", "POST", "PUT", "DELETE"]
        paths: ["/v1alpha/projects/$PROJECT_ID/accounts*"]
    - operation:
        methods: ["OPTIONS", "GET", "POST", "PUT", "DELETE"]
        paths: ["/v1alpha/projects/$PROJECT_ID/policies*"]
    - operation:
        methods: ["OPTIONS", "GET", "POST", "PUT", "DELETE"]
        paths: ["/v1alpha/projects/$PROJECT_ID/datasets*"]
    - operation:
        methods: ["OPTIONS", "POST"]
        paths: ["/v1alpha/projects/$PROJECT_ID/admin*"]
    - operation:
        methods: ["OPTIONS", POST"]
        paths: ["/v1alpha/projects/$PROJECT_ID/auth:isDataProducer"]
    - operation:
        methods: ["OPTIONS", "GET"]
        paths: ["/v1alpha/projects/$PROJECT_ID/products*"]
    - operation:
        methods: ["OPTIONS", "GET", "POST"]
        paths: ["/v1alpha/projects/$PROJECT_ID/procurements*"]
    - operation:
        methods: ["OPTIONS", "GET", "POST"]
        paths: ["/v1alpha/projects/$PROJECT_ID/spots*"]
  - when:
    - key: request.auth.claims[email]
      values: ["$DATA_PRODUCERS"]
