title: "BQDS Spot Fulfillment Manager Role"
description: "Custom BQDS Spot Fulfillment role for the API services to interface with GCP services"
stage: "BETA"
includedPermissions:
- bigquery.tables.create
- bigquery.tables.delete
- bigquery.tables.export
- bigquery.tables.get
- bigquery.tables.getData
- bigquery.tables.update
- bigquery.tables.updateData
- iam.serviceAccounts.signBlob
- pubsub.subscriptions.consume
- storage.buckets.list
- storage.objects.get
- storage.objects.list
