title: "Datashare Pub/Sub Topic Subscriber"
description: "Datashare role for granting attach subscription access to Pub/Sub topics"
stage: "GA"
includedPermissions:
- pubsub.snapshots.seek
- pubsub.subscriptions.consume
- pubsub.topics.attachSubscription
