apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: firebase-jwt
  namespace: datashare
spec:
  origins:
  - jwt:
      issuer: https://securetoken.google.com/$PROJECT_ID
      jwksUri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
      triggerRules:
      - excludedPaths:
        - exact: /healthz
        - exact: /metrics
        - exact: /probe
        - prefix: /_internal/knative
      - excludedPaths:
        - exact: /docs
  principalBinding: USE_ORIGIN
