---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  # global policy per namespace if name is 'default' without targets
  #name: default
  #namespace: datashare-apis
  name: google-jwt
  namespace: gke-system
spec:
  targets:
  - name: istio-ingress
    ports:
    - number: 80
    - number: 443
  origins:
  - jwt:
      issuer: https://securetoken.google.com/$PROJECT_ID
      jwksUri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
      triggerRules:
      - excludedPaths:
        - exact: /healthz
        - exact: /metrics
        - exact: /probe
        - prefix: /_internal/knative
        - prefix: /v1alpha/docs
  principalBinding: USE_ORIGIN
