---
apiVersion: v1
kind: Service
metadata:
  name: dmc-publisher-service-lb
  labels:
    app: dmc-publisher-service
spec:
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 50000
      name: multicast
      targetPort: 50000
  selector:
    app: dmc-publisher-service
    version: v1
