name: Node Lint CI

on: [push]

jobs:
  shared:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, and test for shared
      run: |
        cd shared
        npm install --loglevel verbose
        npm run lint
        npm test
      env:
        CI: true
  entitlement-engine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, and test for entitlements
      run: |
        cd entitlements/bqdsEntitlements
        npm install --loglevel verbose
        npm run lint
        npm test
      env:
        CI: true
  ingestion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and lint for processUpload
      run: |
        cd shared
        npm install
        cd ..
        cp -R ./shared ./ingestion/function/shared/
        cd ingestion/function
        npm install --loglevel verbose
        npm run lint
      env:
        CI: true
