name: Node Lint CI

on: [push]

jobs:
  shared:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, and test for shared
      run: |
        cd $GITHUB_WORKSPACE/shared
        npm install
        npm run lint
        npm test
      env:
        CI: true
  ingestion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and lint for processUpload
      run: |
        rm -rf $GITHUB_WORKSPACE/shared/node_modules/temp_npm_packages/google-api-nodejs-client/node_modules
        npm install -S --prefix $GITHUB_WORKSPACE/shared/temp_npm_packages/google-api-nodejs-client
        rm -rf $GITHUB_WORKSPACE/shared/node_modules
        npm install --prefix $GITHUB_WORKSPACE/shared
        rm -rf GITHUB_WORKSPACE/ingestion/batch/node_modules
        npm install --prefix $GITHUB_WORKSPACE/ingestion/batch
        npm run lint --prefix $GITHUB_WORKSPACE/ingestion/batch
        npm test --prefix $GITHUB_WORKSPACE/ingestion/batch
      env:
        CI: true
